apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-bindings
  namespace: todo-dev
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 30s"  # More frequent for development/testing