apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: todo-dev
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "my-cluster-kafka-bootstrap:9092"  # Pointing to the Strimzi Kafka cluster
  - name: consumerGroup # Optional. Used for input bindings.
    value: "todo-dev-group"
  - name: clientID # Optional. Used as client tracing id by Kafka brokers.
    value: "todo-dev-client"
  - name: authRequired # Required. Whether OAuth2 or SASL authentication is required.
    value: "false"  # No authentication for local dev environment
  - name: maxMessageBytes # Optional. Represents the maximum number of bytes accepted.
    value: 1024
  - name: consumeRetryInterval # Optional. Represent the duration to wait before retrying to consume again.
    value: 1s