apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-dev
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=postgres.default.svc.cluster.local user=postgres password=postgres dbname=todo_dev port=5432 sslmode=disable"
  - name: actorStateStore
    value: "true"
  - name: concurrency
    value: "first-write"