apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-bindings
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 1m"  # Placeholder schedule - actual schedules will be configured per reminder needs